run:
  timeout: 3m

issues:
  # exclude-use-default: true
  exclude-dirs:
    - mocks
  exclude-files:
  - ".*_test.go$"

linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 15
  gocritic:
     disabled-checks:
      - ifElseChain
  gosec:
    excludes:
      # Flags for potentially-unsafe casting of ints, similar problem to globally-disabled G103
      - G115


linters:
  disable-all: true
  enable:
  - gosimple
  - staticcheck
  - unused
  - govet
  - revive
  - gocyclo
  - gosec
  - unconvert
  - dupl
  - nakedret
  - prealloc
  - gocritic