version: "2"
linters:
  default: none
  enable:
    - dupl
    - gocritic
    - gocyclo
    - gosec
    - govet
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G115
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*_test.go$
      - mocks
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
